@tool
extends RefCounted
## Keeps <download_root>/asset_manifest.json (machine-readable) and
## <download_root>/CREDITS.md (regenerated from the manifest) in sync.

const Settings = preload("settings.gd")


static func manifest_path() -> String:
	return Settings.download_root().path_join("asset_manifest.json")


static func credits_path() -> String:
	return Settings.download_root().path_join("CREDITS.md")


static func load_manifest() -> Dictionary:
	if not FileAccess.file_exists(manifest_path()):
		return {"version": 1, "assets": {}}
	var data: Variant = JSON.parse_string(FileAccess.get_file_as_string(manifest_path()))
	if data is Dictionary and data.get("assets") is Dictionary:
		return data
	return {"version": 1, "assets": {}}


## Returns the manifest entry for an asset, or {} if never downloaded.
static func find(source_id: String, asset_id: String) -> Dictionary:
	return load_manifest().assets.get("%s/%s" % [source_id, asset_id], {})


## `main_file` is the res:// path of the scene/material/sky to open.
static func record(asset: Dictionary, source_name: String, resolution: String, folder: String, main_file: String) -> void:
	var manifest := load_manifest()
	var key := "%s/%s" % [asset.source, asset.id]
	var entry: Dictionary = manifest.assets.get(key, {})
	var resolutions: Array = entry.get("resolutions", [])
	if resolution not in resolutions:
		resolutions.append(resolution)
		resolutions.sort_custom(func(a, b): return a.to_int() < b.to_int())
	manifest.assets[key] = {
		"id": asset.id,
		"name": asset.name,
		"source": source_name,
		"source_id": asset.source,
		"type": asset.get("type", ""),
		"url": asset.page_url,
		"license": asset.license,
		"authors": asset.authors,
		"resolutions": resolutions,
		"folder": folder,
		"main_file": main_file,
		"downloaded": Time.get_datetime_string_from_system(true),
	}
	DirAccess.make_dir_recursive_absolute(Settings.download_root())
	var f := FileAccess.open(manifest_path(), FileAccess.WRITE)
	f.store_string(JSON.stringify(manifest, "\t", true))
	f.close()
	_write_credits(manifest)


## Stores extra data (e.g. Terrain3D prep results) on an existing entry.
static func set_extra(source_id: String, asset_id: String, key: String, value: Variant) -> void:
	var manifest := load_manifest()
	var entry_key := "%s/%s" % [source_id, asset_id]
	if not manifest.assets.has(entry_key):
		return
	manifest.assets[entry_key][key] = value
	var f := FileAccess.open(manifest_path(), FileAccess.WRITE)
	f.store_string(JSON.stringify(manifest, "\t", true))


static func _write_credits(manifest: Dictionary) -> void:
	var lines := PackedStringArray([
		"# Third-party asset credits",
		"",
		"Generated by the Asset Commons plugin from `asset_manifest.json`. Do not edit by hand.",
		"",
		"| Asset | Type | Source | Authors | License | Link |",
		"|---|---|---|---|---|---|",
	])
	var keys: Array = manifest.assets.keys()
	keys.sort()
	for key in keys:
		var e: Dictionary = manifest.assets[key]
		var authors := PackedStringArray()
		for author in e.authors:
			authors.append("%s (%s)" % [author, e.authors[author]])
		lines.append("| %s | %s | %s | %s | %s | %s |" % [e.name, e.get("type", "models"), e.source, ", ".join(authors), e.license, e.url])
	lines.append("")
	var f := FileAccess.open(credits_path(), FileAccess.WRITE)
	f.store_string("\n".join(lines))
